//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : AccesoBaseDeDatos.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//
package whatsUPM;



public class AccesoBaseDeDatos {

	public  AccesoBaseDeDatos() {
	
	}
	
	public void insertMensaje() {
	
	}
	
	public void selectMensaje() {
	
	}
	
	public void deleteMensaje() {
	
	}
	
	public boolean conectarBD() {

	    return true;
	}
	
	public void insertChats() {
	
	}
	
	public void selectChats() {
	
	}
	
	public void deleteChats() {
	
	}
	
	public void insertPerfil() {
	
	}
	
	public void selectPerfil() {
	
	}
	
	public void deletePerfil() {
	
	}
	
	public void destroy() {
	
	}
}
