//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : Agenda.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//

package whatsUPM;


import java.util.ArrayList;
import java.util.Date;

public class Agenda implements InterfazAgenda {
	private Boolean esFavorito;
	private Integer idAgenda;
	private String categoria;
	private Date fechaCreacion;
	private ArrayList<Perfil> contactos;


	public  Agenda(ArrayList<Perfil> listaContactos, String categoria, Integer idAgenda) {
	    this.contactos=listaContactos;
	    this.categoria=categoria;
	    this.idAgenda=idAgenda;
	
	}

    public Boolean getEsFavorito() {
        return esFavorito;
    }

    public void setEsFavorito(Boolean esFavorito) {
        this.esFavorito = esFavorito;
    }

    public Integer getIdAgenda() {
        return idAgenda;
    }

    public void setIdAgenda(Integer idAgenda) {
        this.idAgenda = idAgenda;
    }

    public String getCategoria() {
        return categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public ArrayList<Perfil> getContactos() {
        return contactos;
    }

    public void setContactos(ArrayList<Perfil> contactos) {
        this.contactos = contactos;
    }

    public void modificarAgenda() {

	}
	
	public void seleccionarIntegrantesAgenda() {

	}
	
	public void introducirUsuariosAgenda() {

	}
	
	public void destroy() {
	
	}

    @Override
    public void crearAgenda() {

    }

    @Override
    public void marcarComoFavorito() {
	    this.esFavorito=true;

    }

    @Override
    public void cambiarNombreAgenda(String categoria) {
	    this.categoria=categoria;

    }

    @Override
    public void modificarIntegrantes() {

    }

    @Override
    public void eliminarAgenda() {
	    this.destroy();

    }
}
