//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : AutorizacionLDAP.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//

package whatsUPM;


public class AutorizacionLDAP {
	public Usuario Autoriza;


	public  AutorizacionLDAP() {
	
	}
	
	public Boolean consultaUsuario() {
        return null;
	}
	
	public void destroy() {
	
	}
}
