//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : ChatFactoryMethod.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//


package whatsUPM;

import java.util.ArrayList;

public interface ChatFactoryMethod {
	public Chat createChat(ArrayList<Perfil> integrantes) ;
}
