//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : ChatIndividual.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//

package whatsUPM;


import java.util.ArrayList;

public class ChatIndividual extends Chat {

	public  ChatIndividual(ArrayList<Perfil> integrantes) {
	    super(integrantes);
	
	}

	public void destroy() {
	
	}
}
