//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : ChatGrupal.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//


package whatsUPM;

import javafx.scene.image.Image;

import java.util.ArrayList;

public class ChatGrupal extends Chat {
	private Image imagen;
	private String nombre;

	public  ChatGrupal(ArrayList<Perfil> integrantes) {
	
	}
	
	public void setImagen(Image imagen) {
	
	}
	
	public void setNombre(String nombre) {
	
	}
	
	public void introducirUsuariosGrupo() {
	
	}
	
	public void introducirNombreImagenGrupo(String nombre, Image imagen) {
	
	}
	
	public Image getImagen() {
        return null;
	}
	
	public String getNombre() {
        return null;
	}
	
	public ArrayList<Perfil> getUsuarios() {
        return null;
	}
	
	public void destroy() {
	
	}
}
