//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : Chat.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//



package whatsUPM;

import java.util.ArrayList;
import java.util.Date;

public class Chat implements InterfaceChat {
	private Date fecha;
	private ArrayList<Perfil> integrantes;
	private ArrayList<Mensaje> mensajes;


	public Chat(ArrayList<Perfil> integrantes) {
	    this.integrantes=integrantes;
	
	}

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public ArrayList<Perfil> getIntegrantes() {
        return integrantes;
    }

    public void setIntegrantes(ArrayList<Perfil> integrantes) {
        this.integrantes = integrantes;
    }

    public ArrayList<Mensaje> getMensajes() {
        return mensajes;
    }

    public void setMensajes(ArrayList<Mensaje> mensajes) {
        this.mensajes = mensajes;
    }


	public void destroy() {
	
	}

    @Override
    public void enviarMensaje(Mensaje mensaje) {

    }

    @Override
    public void listarMensajes() {

    }

    @Override
    public void visualizarIntegrantes() {

    }

    @Override
    public void anadirIntegrantes() {

    }

    @Override
    public void modificarChat() {

    }

    @Override
    public void eliminarMensaje() {

    }
}
