//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : ChatFactory.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//

package whatsUPM;


import java.util.ArrayList;

public class ChatFactory implements ChatFactoryMethod {
	public Chat createChat(ArrayList<Perfil> integrantes) {
	    if(integrantes.size()==1){
	        return new ChatIndividual(integrantes);
        }else return new ChatGrupal(integrantes);

	}
}
