//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : ChatGrupal.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//


package whatsUPM;

import javafx.scene.image.Image;

import java.util.ArrayList;

public class ChatGrupal extends Chat {
	private Image imagen;
	private String nombre;

	public  ChatGrupal(ArrayList<Perfil> integrantes) {
	    super(integrantes);
	
	}
	
	public void setImagen(Image imagen) {
	this.imagen=imagen;
	}
	
	public void setNombre(String nombre) {
	this.nombre=nombre;
	}
	
	public void introducirUsuariosGrupo() {
	
	}
	
	public void introducirNombreImagenGrupo(String nombre, Image imagen) {
	this.nombre=nombre;
	this.imagen=imagen;
	}
	
	public Image getImagen() {
        return this.imagen;
	}
	
	public String getNombre() {
        return this.nombre;
	}

	public void destroy() {
	
	}
}
