//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : InterfacePerfil.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//

package whatsUPM;


public interface InterfacePerfil {
	public void modificarPerfil();

    public void visualizarPerfil();
}
