//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : InterfaceMensaje.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//


package whatsUPM;

public interface InterfaceMensaje {
	public void marcarComoRecibido();

    public void marcarComoLeido();
}
