//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : InterfazAgenda.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//

package whatsUPM;


public interface InterfazAgenda {

	public void crearAgenda();

    public void marcarComoFavorito();

    public void cambiarNombreAgenda(String categoria);

    public void modificarIntegrantes();

    public void eliminarAgenda();
}
