//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : InterfaceChat.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//
package whatsUPM;



public interface InterfaceChat {

	public void enviarMensaje(Mensaje mensaje);

    public void listarMensajes();

    public void visualizarIntegrantes();

    public void anadirIntegrantes();

    public void modificarChat();

    public void eliminarMensaje();
}
