//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : InterfazUsuario.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//

package whatsUPM;


public interface InterfazUsuario {
	public void cambiarContrasena();
	
	public void crearChat();
	
	public void seleccionarAgendaFavorita();
	
	public void verPerfil();

    public void verAgendas();

    public void verChats();
}
