//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : Mensaje.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//

package whatsUPM;


import java.util.Date;

public class Mensaje implements InterfaceMensaje {
	private String texto;
	private Integer usuarioOrigen;
	private Date fecha;
	private Boolean esRecibido;
	private Boolean esVisto;

	public  Mensaje(String texto, Integer usuarioOrigen) {
	
	}
	
	public void setEsRecibido(Boolean esRecibido) {
	
	}
	
	public void setEsVisto(Boolean esVisto) {
	
	}
	
	public String getTexto() {
        return null;
	}
	
	public Integer getUsuarioOrigen() {
        return null;
	}
	
	public Date getFecha() {
        return null;
	}
	
	public Boolean getEsRecibido() {
        return null;
	}
	
	public Boolean getEsVisto() {
        return null;
	}
	
	public void destroy() {
	
	}

    @Override
    public void marcarComoRecibido() {

    }

    @Override
    public void marcarComoLeido() {

    }
}
