//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : Mensaje.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//

package whatsUPM;


import java.time.LocalDateTime;
import java.util.Date;

public class Mensaje implements InterfaceMensaje {
	private String texto;
	private Integer usuarioOrigen;
	private Date fecha;
	private Boolean esRecibido = false;
	private Boolean esVisto = false;
	private String aliasOrigen;

	public  Mensaje(String texto, Integer usuarioOrigen) {
	    this.texto=texto;
	    this.usuarioOrigen=usuarioOrigen;

	
	}

    public Mensaje(String mensaje, String aliasOrigen) {
	    this.aliasOrigen=aliasOrigen;
	    this.texto=mensaje;
    }

    public String getTexto() {
        return texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    public Integer getUsuarioOrigen() {
        return usuarioOrigen;
    }

    public void setUsuarioOrigen(Integer usuarioOrigen) {
        this.usuarioOrigen = usuarioOrigen;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Boolean getEsRecibido() {
        return esRecibido;
    }

    public void setEsRecibido(Boolean esRecibido) {
        this.esRecibido = esRecibido;
    }

    public Boolean getEsVisto() {
        return esVisto;
    }

    public void setEsVisto(Boolean esVisto) {
        this.esVisto = esVisto;
    }

    public void destroy() {
	
	}

    @Override
    public void marcarComoRecibido() {
	    this.esRecibido=true;

    }

    @Override
    public void marcarComoLeido() {
	    this.esVisto=true;

    }
}
