//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : Perfil.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//

package whatsUPM;


import javafx.scene.image.Image;

public class Perfil implements InterfacePerfil {
	private Image foto;
	private Integer idPerfil;
	private String estado;
	private String descripcion;
	private String alias;

	public Perfil(String alias) {
	
	}
	
	public void setFoto(Image foto) {
	
	}
	
	public void setEstado(String estado) {
	
	}
	
	public void setDescripcion(String descripcion) {
	
	}
	
	public void setAlias(String alias) {
	
	}
	
	public Image getFoto() {

        return null;
	}
	
	public Integer getIdPerfil() {
        return null;
	}
	
	public String getEstado() {
        return null;
	}
	
	public String getDescripcion() {
        return null;
	}
	
	public String getAlias() {
        return null;
	}
	
	public void modificarPerfil() {
	
	}
	
	public void visualizarPerfil() {
	
	}
	
	public void destroy() {
	
	}
}
