//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : Usuario.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//


package whatsUPM;

import java.util.ArrayList;

public class Usuario implements InterfazUsuario {

	private Integer idUsuario;
	private String correo;
	private String contrasena;
	private ArrayList<Agenda> agendas;
	private Perfil perfil;
	private ArrayList<Chat> chats;
	private ChatFactoryMethod chatFactory;



	public Usuario(Integer idUsuario, String correo, String contrasena) {
	    this.idUsuario=idUsuario;
	    this.correo=correo;
	    this.contrasena=contrasena;
	    this.chatFactory=new ChatFactory();
	    this.chats= new ArrayList<>();




	
	}
	public void init(){

        ArrayList<Perfil> integrantes = new ArrayList<>();
        Perfil perfil = new Perfil("pepe");
        integrantes.add(perfil);


        this.crearChat(integrantes);

        ArrayList<Mensaje> mensajes = new ArrayList<>();
        mensajes.add(new Mensaje("Holaaaa", this.idUsuario));
        this.getChats().get(0).setMensajes(mensajes);




    }
	
	public void setContrasena(String contrasena) {
	this.contrasena=contrasena;
	}
	
	public void setAgendas(ArrayList<Agenda> agendas) {
	    this.agendas=agendas;
	
	}
	
	public void setPerfil(Perfil perfil) {
	    this.perfil=perfil;
	
	}
	
	public void setChats(ArrayList<Chat> chats) {
	    this.chats=chats;
	
	}
	
	public Integer getIdUsuario() {
        return this.idUsuario;
	}
	
	public String getCorreo() {
        return this.correo;
	}
	
	public String getContrasena() {
        return this.contrasena;
	}
	
	public ArrayList<Agenda> getAgendas() {
        return this.agendas;
	}
	
	public Perfil getPerfil() {
        return this.perfil;
	}
	
	public ArrayList<Chat> getChats() {
        return this.chats;
	}
	
	public void destroy() {
	
	}

    @Override
    public void cambiarContrasena() {

    }

    @Override
    public void crearChat(ArrayList<Perfil> perfiles) {

	    this.chats.add(this.chatFactory.createChat(perfiles));
    }

    @Override
    public void seleccionarAgendaFavorita() {

    }

    @Override
    public void verPerfil() {

    }

    @Override
    public void verAgendas() {

    }

    @Override
    public void verChats() {

    }
}
