//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : Usuario.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//


package whatsUPM;

import javafx.scene.image.Image;

import java.util.ArrayList;


public class Usuario implements InterfazUsuario {

    private Integer idUsuario;
    private String correo;
    private String contrasena;
    private ArrayList<Agenda> agendas;
    private Perfil perfil;
    private ArrayList<Chat> chats;
    private ChatFactoryMethod chatFactory;


    public Usuario(Integer idUsuario,  String correo, String contrasena) {
        this.idUsuario = idUsuario;
        this.correo = correo;
        this.contrasena = contrasena;
        this.chatFactory = new ChatFactory();
        this.chats = new ArrayList<>();
        this.agendas = new ArrayList<>();


    }

    public void init() {


        ArrayList<Perfil> integrantes = new ArrayList<>();

        Perfil perfil = new Perfil("Asier Armenteros");
        integrantes.add(perfil);
        perfil.setFoto(new Image("data/OtherUser.png"));
        perfil.setDescripcion("Mecánico a tiempo completo");

        Agenda agenda = new Agenda(integrantes, "Amigos", 0);
        this.agendas.add(agenda);

        this.crearChat(this.agendas.get(0).getContactos());

        ArrayList<Mensaje> mensajes = new ArrayList<>();
        mensajes.add(new Mensaje("Respondemeee!", this.idUsuario));
        this.getChats().get(0).setMensajes(mensajes);

        this.setPerfil(new Perfil("Mario Jurado"));
        this.getPerfil().setFoto(new Image("data/mainUser.jpg"));
        this.getPerfil().setDescripcion("Hola, soy Jacinto, ¡un apasionado por las motos y la velocidad!");


    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    public void setAgendas(ArrayList<Agenda> agendas) {
        this.agendas = agendas;

    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    public void setChats(ArrayList<Chat> chats) {
        this.chats = chats;

    }

    public Integer getIdUsuario() {
        return this.idUsuario;
    }

    public String getCorreo() {
        return this.correo;
    }

    public String getContrasena() {
        return this.contrasena;
    }

    public ArrayList<Agenda> getAgendas() {
        return this.agendas;
    }

    public Perfil getPerfil() {
        return this.perfil;
    }

    public ArrayList<Chat> getChats() {
        return this.chats;
    }

    public void destroy() {

    }

    @Override
    public void cambiarContrasena() {

    }

    @Override
    public void crearChat(ArrayList<Perfil> perfiles) {

        this.chats.add(this.chatFactory.createChat(perfiles));
    }

    @Override
    public void seleccionarAgendaFavorita() {

    }

    @Override
    public void verPerfil() {

    }

    @Override
    public void verAgendas() {

    }

    @Override
    public void verChats() {

    }

    public void getData() {

    }
}
