//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WhatsUPM GT22-8
//  @ File Name : Usuario.java
//  @ Date : 26/05/2018
//  @ Author : 
//
//


package whatsUPM;

import java.util.ArrayList;

public class Usuario implements InterfazUsuario {

	private Integer idUsuario;
	private String correo;
	private String contrasena;
	private ArrayList<Agenda> agendas;
	private Perfil perfil;
	private ArrayList<Chat> chats;
	private ChatFactoryMethod chatFactory;



	public Usuario(Integer idUsuario, String correo, String contrasena) {
	
	}
	
	public void setContrasena(String contrasena) {
	
	}
	
	public void setAgendas(ArrayList<Agenda> agendas) {
	
	}
	
	public void setPerfil(Perfil perfil) {
	
	}
	
	public void setChats(ArrayList<Chat> chats) {
	
	}
	
	public Integer getIdUsuario() {
        return null;
	}
	
	public String getCorreo() {
        return null;
	}
	
	public String getContrasena() {
        return null;
	}
	
	public ArrayList<Agenda> getAgendas() {
        return null;
	}
	
	public Perfil getPerfil() {
        return null;
	}
	
	public ArrayList<Chat> getChats() {
        return null;
	}

	
	public void crearChat(Perfil perfilUsuario) {
	
	}
	
	public void destroy() {
	
	}

    @Override
    public void cambiarContrasena() {

    }

    @Override
    public void crearChat() {

    }

    @Override
    public void seleccionarAgendaFavorita() {

    }

    @Override
    public void verPerfil() {

    }

    @Override
    public void verAgendas() {

    }

    @Override
    public void verChats() {

    }
}
